version: "3.3"

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    networks:
      - default
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    
  nats:
    image: nats
    container_name: nats
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    env_file: docker-compose.env
    ports:
      - '2181:2181'
    volumes:
      - ../zookeeper/data:/bitnami/zookeeper
    networks:
      - default

# Make the externally created network "gateway" available as network "default"
networks:
  default:
    external: 
      name: gateway
volumes:
  letsencrypt: