version: "3.3"

services:
  nats:
    image: nats
    container_name: nats
    networks:
      - main-network
  
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    networks:
      - main-network
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - $PWD/.caddy/data:/data
      - $PWD/.caddy/config:/config

  mongo:
    image: mongo 
    container_name: db
    restart: always
    env_file: docker-compose.env
    ports:
      - "27017:27017"
    volumes:
      - /usr/local/var/mongodb/:/data/db
    networks:
      - main-network

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    env_file: docker-compose.env
    ports:
      - '2181:2181'
    volumes:
      - ../zookeeper/:/bitnami/zookeeper
    networks:
      - main-network

networks:
  main-network:
    external: true