version: "3.3"

services:
  nats:
    image: nats
    container_name: nats
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    env_file: docker-compose.env
    ports:
      - '2181:2181'
    volumes:
      - ../zookeeper/data:/bitnami/zookeeper
    networks:
      - default

# Make the externally created network "gateway" available as network "default"
networks:
  default:
    external: 
      name: gateway