version: "3.3"

services:
  traefik:
    image: traefik:v2.1.1
    container_name: traefik 
    restart: "always"
    command:
      - --providers.docker
      - --api=true
      - --api.insecure=true
      - --log.level=debug
      - --providers.docker.exposedbydefault=false
      # TLS configuration
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesResolvers.le.acme.email=frishi@me.com
      - --certificatesResolvers.le.acme.storage=/acme.json
      # used during the challenge
      # - --certificatesresolvers.le.acme.httpChallenge=true
      - --certificatesResolvers.le.acme.dnsChallenge=true

      - --certificatesResolvers.le.acme.dnsChallenge.provider=digitalocean
      # - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
      # LE staging
      # - --certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
    labels:
      - traefik.http.routers.api.rule=Host(`services.rishighan.com`) && PathPrefix(`/dashboard`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.tls.certresolver=le
    environment: 
      - "DO_AUTH_TOKEN=721f972b5631edd716c0e574d98097a22c09e1d53bc4ecbbba8ee1f724eed41b"
    ports:
      # Port 443 is used for HTTP trafic
      - "80:80"
      # Port 443 is used for HTTPS trafic
      - "443:443"
      - "8080:8080"
    volumes:
      # production
      - letsencrypt/acme.json:/acme.json
      # The docker socket is mounted for auto-discovery of new services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      # Attach the traefik container to the default network (which is the global "gateway" network)
      - default
    
  nats:
    image: nats
    container_name: nats
    labels:
      - traefik.enable=false
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment: 
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    labels:
      - traefik.enable=false
    ports:
      - '2181:2181'
    volumes:
      - ../zookeeper/data:/bitnami/zookeeper
    networks:
      - default

# Make the externally created network "gateway" available as network "default"
networks:
  default:
    external: 
      name: gateway