version: "3.3"

services:
  traefik:
    image: traefik
    container_name: traefik 
    restart: "always"
    environment: 
      - DO_AUTH_TOKEN=721f972b5631edd716c0e574d98097a22c09e1d53bc4ecbbba8ee1f724eed41b
    command:
      - --providers.docker=true
      # - --api.insecure=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --certificatesResolvers.sample.acme.email=frishi@me.com
      - --certificatesResolvers.sample.acme.storage=acme.json
      - --certificatesResolvers.sample.acme.httpChallenge.entryPoint=web
      - --certificatesresolvers.sample.acme.dnschallenge=true
      - --certificatesresolvers.sample.acme.dnschallenge.provider=digitalocean
    labels:
      - traefik.http.routers.web.rule=Host(`localhost`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.websecure.rule=Host(`localhost`)
      - traefik.http.routers.websecure.entrypoints=websecure
      - traefik.http.routers.websecure.tls
      - traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=myAuth
      # - traefik.http.middlewares.myAuth.basicauth.users=admin:$apr1$7EmZ/3DV$HAzUj/8s0kwszb1ExlWY9.
    ports:
      # Port 443 is used for HTTP trafic
      - "80:80"
      # Port 443 is used for HTTPS trafic
      - "443:443"
      # Port 8080 is used for traefik's own dashboard
      - "8080:8080"
    volumes:
      # Here is the mount of the traefik config
      # - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./acme.json:/acme.json
      # The docker socket is mounted for auto-discovery of new services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      # Attach the traefik container to the default network (which is the global "gateway" network)
      - default
    
  nats:
    image: nats
    container_name: nats
    labels:
      - traefik.enable=false
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment: 
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    labels:
      - traefik.enable=false
    ports:
      - '2181:2181'
    volumes:
      - ../zookeeper/data:/bitnami/zookeeper
    networks:
      - default

# Make the externally created network "gateway" available as network "default"
networks:
  default:
    external: 
      name: gateway