version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik 
    restart: unless-stopped
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web=true"
      - "--entrypoints.web.address=:80"
    labels:
      # Dashboard
      - "traefik.http.routers.api.rule=Host(`services.rishighan.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - 'traefik.http.routers.api.entrypoints=web'
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=frishi:$$apr1$$oGNy.xU2$$2C97eMH1JEej75Xx7bl4U1"

    ports:
      # Port 443 is used for HTTP trafic
      - "80:80"
      # Port 443 is used for HTTPS trafic
      - "443:443"
    volumes:
      # production
      - /opt/traefik/:/opt/traefik/
      # The docker socket is mounted for auto-discovery of new services
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      # Attach the traefik container to the default network (which is the global "gateway" network)
      - default
    
  nats:
    image: nats
    container_name: nats
    labels:
      - traefik.enable=false
    networks:
      - default

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment: 
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    labels:
      - traefik.enable=false
    ports:
      - '2181:2181'
    volumes:
      - ../zookeeper/data:/bitnami/zookeeper
    networks:
      - default

# Make the externally created network "gateway" available as network "default"
networks:
  default:
    external: 
      name: gateway